version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PWD: default
      DATABASE_NAME: loommerce
    # command: sh -c "npm run populate-db && npm run start"

  postgres:
    image: postgres:15
    container_name: postgres_loomi
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: default
      POSTGRES_DB: loommerce
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
